[package]
name = "revy-raknet"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "RevyCraft-owned bounded RakNet transport state machine."

[dependencies]
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
